"""Report writer for EcoReport AI.

Assembles narrative sections, tables, and figure references into:
  - reports/latest_report.md  (Markdown)
  - reports/latest_report.json (all numeric evidence)

The evidence store is the single source of truth. All numbers in the
Markdown report originate from the evidence store, implementing the
hallucination-prevention architecture from course_raw_notes.md.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from eco_report_ai.reporting.nlg import NarrativeGenerator
from eco_report_ai.utils.io import ensure_dir, save_json

logger = logging.getLogger(__name__)


class ReportWriter:
    """Assembles and writes the final economic report.

    Args:
        output_dir: Root output directory (e.g., "reports/").
        figures_dir: Directory containing chart PNG files.
        report_filename: Base filename without extension.
        nlg: NarrativeGenerator instance.
    """

    def __init__(
        self,
        output_dir: str | Path = "reports",
        figures_dir: str | Path = "reports/figures",
        report_filename: str = "latest_report",
        nlg: Optional[NarrativeGenerator] = None,
    ) -> None:
        self.output_dir = Path(output_dir)
        self.figures_dir = Path(figures_dir)
        self.report_filename = report_filename
        self.nlg = nlg or NarrativeGenerator()

    def write_markdown(self, evidence: dict[str, Any]) -> str:
        """Generate and write the Markdown economic report.

        Args:
            evidence: Complete evidence store dict.

        Returns:
            Path to the written Markdown file.
        """
        ensure_dir(self.output_dir)

        run_time = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        best_model = evidence.get("best_model", "N/A")
        data_source = evidence.get("data_source", "sample")

        # ── Build sections ────────────────────────────────────────────────────
        exec_summary = self.nlg.generate_executive_summary(evidence)
        data_overview = self.nlg.generate_data_overview(evidence)
        econ_findings = self.nlg.generate_econometric_findings(evidence)
        forecast_section = self.nlg.generate_forecast_section(evidence)
        risks_section = self.nlg.generate_risks(evidence)
        repro_section = self.nlg.generate_reproducibility(evidence)

        # ── Model comparison table ─────────────────────────────────────────────
        model_comparison_table = _build_model_comparison_table(
            evidence.get("model_metrics", {})
        )

        # ── Figure references ──────────────────────────────────────────────────
        fig_historical = _figure_ref("historical_series.png", "Historical Macro Series")
        fig_forecast = _figure_ref("forecast_plot.png", f"Forecast — {best_model}")
        fig_comparison = _figure_ref("model_comparison.png", "Model Comparison")

        # ── Assemble document ─────────────────────────────────────────────────
        doc = f"""# EcoReport AI — Economic Analysis Report

> **Generated**: {run_time}  
> **Data source**: {data_source}  
> **Best model**: {best_model}

---

## 1. Executive Summary

{exec_summary}

---

## 2. Data Overview

{data_overview}

{fig_historical}

---

## 3. Econometric Findings

{econ_findings}

---

## 4. Forecast Results

{forecast_section}

{fig_forecast}

---

## 5. Model Comparison

{model_comparison_table}

{fig_comparison}

---

## 6. Risks & Limitations

{risks_section}

---

## 7. Reproducibility

{repro_section}

---

*Report generated by [EcoReport AI](https://github.com/eco-report-ai) — combining econometrics, ML, and constrained generative AI.*
"""

        md_path = self.output_dir / f"{self.report_filename}.md"
        md_path.write_text(doc, encoding="utf-8")
        logger.info("Markdown report written: %s (%d bytes)", md_path, md_path.stat().st_size)
        return str(md_path)

    def write_json(self, evidence: dict[str, Any]) -> str:
        """Serialize the complete evidence store to JSON.

        Args:
            evidence: Evidence store dict containing all numeric outputs.

        Returns:
            Path to the written JSON file.
        """
        json_path = self.output_dir / f"{self.report_filename}.json"
        save_json(evidence, json_path)
        logger.info("JSON evidence written: %s", json_path)
        return str(json_path)

    def write_all(self, evidence: dict[str, Any]) -> tuple[str, str]:
        """Write both Markdown and JSON reports.

        Args:
            evidence: Complete evidence store.

        Returns:
            Tuple of (md_path, json_path).
        """
        md_path = self.write_markdown(evidence)
        json_path = self.write_json(evidence)
        return md_path, json_path


def _figure_ref(filename: str, alt_text: str) -> str:
    """Build a Markdown image reference.

    Args:
        filename: PNG filename (relative to figures dir).
        alt_text: Alt text for accessibility.

    Returns:
        Markdown image tag.
    """
    return f"![{alt_text}](figures/{filename})"


def _build_model_comparison_table(model_metrics: dict[str, Any]) -> str:
    """Build a Markdown table comparing model metrics.

    Args:
        model_metrics: Dict mapping model_name → {mae, rmse, mape}.

    Returns:
        Markdown table string.
    """
    if not model_metrics:
        return "_No model metrics available._"

    header = "| Model | MAE | RMSE | MAPE (%) |\n|-------|-----|------|----------|\n"
    rows: list[str] = []

    for model_name, metrics in model_metrics.items():
        mae_val = metrics.get("mae", float("nan"))
        rmse_val = metrics.get("rmse", float("nan"))
        mape_val = metrics.get("mape", float("nan"))

        mae_str = f"{mae_val:.4f}" if isinstance(mae_val, float) and mae_val == mae_val else "N/A"
        rmse_str = f"{rmse_val:.4f}" if isinstance(rmse_val, float) and rmse_val == rmse_val else "N/A"
        mape_str = f"{mape_val:.2f}" if isinstance(mape_val, float) and mape_val == mape_val else "N/A"

        rows.append(f"| {model_name} | {mae_str} | {rmse_str} | {mape_str} |")

    return header + "\n".join(rows)
